class Headers:
    def get_headers() -> list:
        return [
            "Date",
            "Amount",
            "Type",
            "Transaction ID",
            "Description",
            "Tax Deductible",
            "Category"
        ]


class Tags:
    def get_tags() -> dict:
        return {
            "acorns": "Investment",
            "royal farms": "Gas",
            "taco": "Food",
            "eyez": "Medical",
            "suntrust": "Car Payment",
            "redzone blitz": "Food",
            "instacart": "Groceries",
            "cleaners": "Uniforms",
            "matchbox": "Food",
            "exxon": "Gas",
            "restaurant": "Food",
            "safeway": "Groceries",
            "usps": "Postage and Shipping",
            "food lion": "Groceries",
            "whip clean": "Cleaners",
            "metro": "Transportation",
            "gates hudson": "Rent",
            "ascend apollo": "Rent",
            "USAA P&C": "Insurance",
            "tight n up": "Haircut",
            "kfc": "Food",
            "dd/br": "Food",
            "heroku": "Business Expense",
            "google fi": "Cell Phone",
            "google apps": "Business Expense",
            "zipcar": "Transportation",
            "grill": "Food",
            "popeyes": "Food",
            "fedex": "Postage and Shipping",
            "uber": "Transportation",
            "lyft": "Transportation",
            "mcdonald": "Food",
            "dunkin": "Food",
            "amtrak": "Transportation",
            "rite aid": "Pharmacy",
            "vre": "Transportation",
            "cox": "Business Expense",
            "winn dixie": "Groceries",
            "marathon": "Gas",
            "spotify": "Subscription",
            "peabodys": "Food",
            "grand prix": "Entertainment",
            "budget": "Transportation",
            "seafood": "Food",
            "speedway": "Gas",
            "digit": "Savings",
            "cigar": "Entertainment",
            "roadhouse": "Food",
            "eleven": "Misc",
            "stash": "Savings",
            "grubhub": "Food",
            "sunoco": "Misc",
            "potomac": "Utilities",
            "fuel": "Gas",
            "amazon prime": "Subscription",
            "five guys": "Food",
            "shell oil": "Gas",
            "haagen": "Food",
            "citi": "Credit Card",
            "julia": "Gift",
            "discover": "Credit Cards",
            "shoppers": "Groveries",
            "liquor": "Misc",
            "GoFndMe": "Donations",
            "pizza": "Food",
            "sling": "Cable",
            "uszoom": "Postage and Shipping",
            "snack": "Food",
            "zelle": "Gift",
            "pro wash": "Car Expense",
            "chase": "Credit Cards",
            "ups store": "Postage and Shipping",
            "ruby tuesday": "Food",
            "amzn mktp": "Misc",
            "amzn.com": "Misc",
            "comcast": "Utilities",
            "taste": "Food",
            "venmo": "Gift",
            "transferwise": "Savings",
            "home depot": "Home Improvement",
            "united": "Transportation",
            "puyallu": "Gift",
            "walmart": "Misc",
            "qdoba": "Food",
            "toyota": "Car Expense",
            "marc": "Transportation",
            "alaska air": "Transportation",
            "walgreens": "Parmacy",
            "food": "food",
            "va abc": "Misc",
            "oyster": "Food",
            "oxon hill": "Entertainment",
            "garage": "Transportation",
            "clini": "Heathcare",
            "lounge": "Alcohol & Bars",
            "wendys": "Food",
            "ftd": "Gift",
            "robinhood": "Investment",
            "target": "Shopping",
            "wine": "Alcohol & Bars",
            "publix": "Groceries",
            "car wash": "Car Expense",
            "american air": "Transportation",
            "auto parts": "Car Expense",
            "synchrony": "Credit Card",
            "ethiopi": "Food",
            "longhorn": "Food",
            "ivy city": "Misc",
            "zippy": "Moving Expense",
            "ourisman": "Car Expense",
            "groupon": "Gift",
            "lowes": "Home Improvement",
            "carolina kitchen": "Food",
            "parking": "Transportation",
            "stogie": "Alcohol & Bars",
            "washington gas": "Utilities",
            "improv": "Entertainment",
            "lucky strike": "Entertainment",
            "dirty habit": "Alcohol & Bars",
            "decades": "Entertainment",
            "pharm": "Pharmacy",
            "CHRYSLER": "Car Expense",
            "paypal inst xfer": "Misc",
            "office depot": "Business Expense",
            "car was": "Car Expense",
            "xfinity": "Utilities",
            "donate": "Donation",
            "wayfair": "Home Improvement",
            "couchsurfing": "Travel",
            "famvibe": "Gift",
            "coffe": "Food",
            "shang hai": "Food",
            "dhsmv": "Car Expense",
            "noodles": "Food",
            "spirit air": "Transportation",
            "ggc": "Entertainment",
            "mandu": "Food",
            "m street": "Entertainment",
            "yardi": "Rent",
            "rewind": "Food",
            "the smith": "Food",
            "etsy": "Misc",
            "new meaning": "Clothing",
            "calm": "Heathcare",
            "lasani": "Food",
            "expression tees": "Clothing",
            "bozzelli": "Food",
            "clothing": "Clothing",
            "allianz": "Travel",
            "fashion": "Clothing",
            "boredwalk": "Clothing",
            "blissy": "Home Improvement",
            "deli": "Food",
            "moxy": "Entertainment",
            "sugarcane": "Food",
            "flight deck": "Entertainment",
            "station 4": "Food",
            "testing": "Education",
            "chipotle": "Food",
            "edible arrangements": "Gift",
            "fl dept": "Business Expense",
            "florida dept": "Business Expense",
            "notarize": "Business Expense",
            "jimmy johns": "Food",
            "shirt": "Clothing",
            "forman mills": "Clothing",
            "secure finger": "Business Expense",
            "las vegas nv": "Entertainment",
            "fort belvoir": "Groceries",
            "cafe": "Food",
            "pusserslanding": "Food",
            "market basket": "Food",
            "golf": "Entertainment",
            "javed iqbal": "Medical",
            "jomashop": "Gift",
            "xi an ao peng": "Clothing",
            "speed deals": "Clothing",
            "the grove": "Misc",
            "crain mitchell": "Misc",
            "bowie bowie": "Misc",
            "stevie p": "Misc",
            "JBM": "Misc",
            "flyer": "Misc"
        }
